/**
 * CIRCULUS — Seed Demo Fixtures & Industrial Material Knowledge Base (India Edition)
 * Written with clean, high-definition product imagery and 10th-grade friendly explanations.
 */

import { MaterialPassport, MarketplaceListing, MatchRecommendation, OwnershipEvent } from "../types";

export const DEMO_PRESET_MATERIALS = [
  {
    id: "preset-aluminium-6063",
    name: "Aluminium Window & Frame Scrap",
    simpleName: "Clean Aluminium Metal Scrap",
    category: "non_ferrous" as const,
    grade: "Grade 6063 T6 (Clean & Pure)",
    simpleDescription: "Clean silver aluminium cutoffs from factory window frames. Over 98% pure metal, no paint, ready to melt.",
    whatBecomes: "New solar panel rails, bicycle frames, and drink cans.",
    greenFact: "Melting recycled aluminium uses 95% less power than mining raw bauxite rock!",
    image: "https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80",
    quantity: 18.5,
    estimatedInrPerMT: 205000,
    state: "Gujarat",
    city: "Sanand (Ahmedabad)",
    spcb: "GPCB (Gujarat)",
    hsn: "76020010",
    eprCategory: "Non-Ferrous Recyclable Metal",
  },
  {
    id: "preset-rpet-flakes",
    name: "Washed Clear Plastic Bottle Flakes",
    simpleName: "Clean Recycled Plastic Flakes (rPET)",
    category: "plastic" as const,
    grade: "Food-Grade Clean Flakes (AA Quality)",
    simpleDescription: "Crushed, hot-water washed clear water and soda bottles. Super clean and dry, ready for new products.",
    whatBecomes: "New plastic bottles, soft polyester t-shirts, and jacket fleece.",
    greenFact: "Keeps 24,000 kg of plastic trash out of rivers and dumpyards!",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    quantity: 24.0,
    estimatedInrPerMT: 84000,
    state: "Maharashtra",
    city: "Pune (Chakan)",
    spcb: "MPCB (Maharashtra)",
    hsn: "39076100",
    eprCategory: "Category 1 Rigid Plastic Packaging",
  },
  {
    id: "preset-cardboard-boxes",
    name: "Compressed Brown Cardboard Bundles",
    simpleName: "Recycled Kraft Cardboard Bales",
    category: "paper_cardboard" as const,
    grade: "Grade OCC-11 (Old Corrugated Containers)",
    simpleDescription: "Clean, dry brown cardboard boxes compressed into tight square bales. Ready for water-pulping.",
    whatBecomes: "New parcel packaging boxes, egg trays, and paper bags.",
    greenFact: "Saves over 340 mature forest trees from being cut down for paper pulp!",
    image: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    quantity: 35.0,
    estimatedInrPerMT: 15500,
    state: "Haryana",
    city: "Gurugram / Manesar",
    spcb: "HSPCB (Haryana)",
    hsn: "47071000",
    eprCategory: "Paper & Packaging Circular Stream",
  },
  {
    id: "preset-ewaste-pcb",
    name: "Server & Computer Motherboards (PCBs)",
    simpleName: "High-Grade E-Waste Circuit Boards",
    category: "ewaste" as const,
    grade: "Class 1 High-Grade Gold/Copper Plated",
    simpleDescription: "De-populated green circuit boards with gold contacts and copper trace lines from decommissioned data centers.",
    whatBecomes: "Refined pure copper ingots, recycled gold, silver, and palladium.",
    greenFact: "Recycling 1 ton of PCBs recovers more gold than mining 40 tons of raw rock ore!",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    quantity: 4.5,
    estimatedInrPerMT: 320000,
    state: "Karnataka",
    city: "Bengaluru (Peenya)",
    spcb: "KSPCB (Karnataka)",
    hsn: "85480000",
    eprCategory: "CPCB E-Waste Schedule I",
  },
  {
    id: "preset-glass-cullet",
    name: "Clean Color-Sorted Glass Cullet",
    simpleName: "Recycled Glass Beverage Bottles",
    category: "glass" as const,
    grade: "IS 5623 Soda-Lime Flint Cullet",
    simpleDescription: "Crushed transparent glass bottles and jars, magnetically cleared of metal caps and paper labels.",
    whatBecomes: "New glass bottles, energy-saving fiberglass insulation, and reflective road markings.",
    greenFact: "Glass can be melted and reformed 100% infinitely with zero loss in quality!",
    image: "https://images.unsplash.com/photo-1577705998148-6da4f3963bc8?auto=format&fit=crop&w=800&q=80",
    quantity: 45.0,
    estimatedInrPerMT: 4200,
    state: "Gujarat",
    city: "Jhagadia (Bharuch)",
    spcb: "GPCB (Gujarat)",
    hsn: "70010000",
    eprCategory: "Container Glass Circular Stream",
  },
  {
    id: "preset-wood-pallets",
    name: "Reclaimed Pine Logistics Pallet Cutoffs",
    simpleName: "Industrial Timber Pallet Scrap",
    category: "wood" as const,
    grade: "Grade A Reusable Industrial Timber",
    simpleDescription: "Dry debarked seasoned softwood pine planks from shipping pallets. Clean and free of toxic chemicals.",
    whatBecomes: "Refurbished warehouse pallets, engineered particle boards, and clean bio-briquettes.",
    greenFact: "Sequesters atmospheric carbon and reduces pressure on natural forest reserves.",
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=800&q=80",
    quantity: 28.0,
    estimatedInrPerMT: 6500,
    state: "Maharashtra",
    city: "Bhiwandi (Thane)",
    spcb: "MPCB (Maharashtra)",
    hsn: "44013900",
    eprCategory: "Bio-Based Logistics Stream",
  },
  {
    id: "preset-textile-cotton",
    name: "Pre-Consumer Knitted Cotton Fabric Waste",
    simpleName: "Garment Factory Cutting Scraps (Chindi)",
    category: "textile" as const,
    grade: "100% Combed Cotton Single Jersey",
    simpleDescription: "Clean, unsoiled virgin fabric trimmings from garment factory cutting tables. Sorted by color.",
    whatBecomes: "Spun recycled cotton yarn, automotive sound insulation felt, and heavy industrial wiping rags.",
    greenFact: "Saves 20,000 liters of agricultural fresh water per kilogram of recycled cotton fiber!",
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80",
    quantity: 15.0,
    estimatedInrPerMT: 31000,
    state: "Tamil Nadu",
    city: "Tiruppur",
    spcb: "TNPCB (Tamil Nadu)",
    hsn: "63109010",
    eprCategory: "Pre-Consumer Textile Circular Stream",
  },
  {
    id: "preset-rubber-crumb",
    name: "Shredded Truck Tire Rubber Granules",
    simpleName: "End-of-Life Tire Rubber Crumbs",
    category: "rubber" as const,
    grade: "Grade 30-Mesh Steel-Free Rubber Crumb",
    simpleDescription: "Mechanically ambient shredded vulcanized truck tire rubber, 99.9% steel wire magnetically separated.",
    whatBecomes: "Crumb rubber modified bitumen for highways, sports running tracks, and gym safety tiles.",
    greenFact: "Eliminates toxic tire dumps and creates weather-resistant high-grip road surfaces.",
    image: "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=800&q=80",
    quantity: 30.0,
    estimatedInrPerMT: 28500,
    state: "Gujarat",
    city: "Vapi (Valsad)",
    spcb: "GPCB (Gujarat)",
    hsn: "40040000",
    eprCategory: "CPCB Tyre EPR Waste Management",
  },
  {
    id: "preset-organic-biomass",
    name: "Sugarcane Bagasse Biomass Pellets",
    simpleName: "Agro-Biomass Green Fuel Pellets",
    category: "organic" as const,
    grade: "Industrial Biofuel Grade A (High GCV)",
    simpleDescription: "Compressed dry fibrous sugarcane residue pellets. Clean, free-flowing, and carbon-neutral bio-feedstock.",
    whatBecomes: "Clean co-firing fuel for power plants, SATAT compressed biogas, and biodegradable tableware.",
    greenFact: "Replaces dirty fossil coal and completely eliminates hazardous agricultural stubble burning.",
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80",
    quantity: 80.0,
    estimatedInrPerMT: 3800,
    state: "Punjab",
    city: "Ludhiana",
    spcb: "PPCB (Punjab)",
    hsn: "14049090",
    eprCategory: "Agro-Biomass Renewable Resource",
  },
  {
    id: "preset-copper-wire",
    name: "Bright Copper Electric Cable Scrap",
    simpleName: "Pure Shiny Copper Wire Scrap",
    category: "non_ferrous" as const,
    grade: "Berry / Barley Grade (99.9% Pure)",
    simpleDescription: "Stripped shiny copper wires from industrial electric panels. No rubber coating, top conductivity.",
    whatBecomes: "Electric vehicle motor wires, transformer coils, and home wiring.",
    greenFact: "Copper can be melted and reused infinite times without losing strength!",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    quantity: 12.0,
    estimatedInrPerMT: 740000,
    state: "Tamil Nadu",
    city: "Hosur (Bangalore Border)",
    spcb: "TNPCB (Tamil Nadu)",
    hsn: "74040012",
    eprCategory: "High-Value Non-Ferrous Metal",
  },
  {
    id: "preset-hms-steel",
    name: "Heavy Steel Beams & Rods Scrap",
    simpleName: "Solid Iron & Steel Heavy Scrap",
    category: "ferrous" as const,
    grade: "HMS 1/2 Structural Steel (Thick >6mm)",
    simpleDescription: "Solid heavy steel beams, pillars, and cut pipes from construction. Thick iron ready for steel furnaces.",
    whatBecomes: "New TMT steel bars for strong houses and railway tracks.",
    greenFact: "Saves 97 tons of coal smoke compared to smelting raw iron in giant furnaces.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
    quantity: 65.0,
    estimatedInrPerMT: 39500,
    state: "Odisha",
    city: "Jajpur (Kalinganagar)",
    spcb: "OSPCB (Odisha)",
    hsn: "72044900",
    eprCategory: "Ferrous Secondary Resource",
  },
  {
    id: "preset-fly-ash",
    name: "Fine Power Plant Fly Ash Powder",
    simpleName: "Grey Chimney Mineral Powder (Fly Ash)",
    category: "fly_ash" as const,
    grade: "Class F Pozzolanic Fine Powder",
    simpleDescription: "Dry, ultra-fine grey powder collected from clean electricity plant chimneys. Acts like magic glue in cement.",
    whatBecomes: "Strong waterproof cement, eco-friendly grey bricks, and highway roads.",
    greenFact: "Replaces traditional cement powder, preventing 96,000 kg of carbon smoke!",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    quantity: 120.0,
    estimatedInrPerMT: 950,
    state: "Chhattisgarh",
    city: "Korba",
    spcb: "CECB (Chhattisgarh)",
    hsn: "26211000",
    eprCategory: "Thermal Power Eco-Byproduct",
  },
  {
    id: "preset-cd-aggregate",
    name: "Crushed Concrete Stone Gravel",
    simpleName: "Recycled Stone Gravel (10-20mm)",
    category: "construction_demolition" as const,
    grade: "IS 383 Clean Recycled Gravel Class II",
    simpleDescription: "Crushed clean stone and concrete from old buildings. Washed and separated by size for new building work.",
    whatBecomes: "Footpath interlocking pavers, garden tiles, and highway road base.",
    greenFact: "Saves mountain rocks and hills from being blasted with dynamite.",
    image: "https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?auto=format&fit=crop&w=800&q=80",
    quantity: 90.0,
    estimatedInrPerMT: 620,
    state: "Delhi NCR",
    city: "Noida Sector 68",
    spcb: "UPPCB (Uttar Pradesh)",
    hsn: "68109990",
    eprCategory: "Construction Recycling Stream",
  },
  {
    id: "preset-gbfs-slag",
    name: "Water-Cooled Blast Furnace Slag Sand",
    simpleName: "Vitreous Slag Sand (GBFS)",
    category: "slag" as const,
    grade: "IS 12089 Slag for Green Cement",
    simpleDescription: "Glassy sand produced when molten iron cools with high-pressure water. Highly resistant to saltwater.",
    whatBecomes: "Durable marine cement for sea bridges, ports, and dams.",
    greenFact: "Stops illegal river sand mining by providing factory-made sand.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    quantity: 140.0,
    estimatedInrPerMT: 1850,
    state: "Karnataka",
    city: "Ballari (Toranagallu)",
    spcb: "KSPCB (Karnataka)",
    hsn: "26190010",
    eprCategory: "Industrial Mineral Byproduct",
  },
];

export const INITIAL_MATERIAL_PASSPORTS: MaterialPassport[] = [
  {
    id: "CUS-AL-6063-GJ",
    title: "Clean Aluminium Window & Profile Scrap (Grade 6063)",
    materialType: "Aluminium Scrap",
    category: "non_ferrous",
    grade: "Grade 6063 T6 (Clean)",
    quantityMT: 18.5,
    reusabilityScore: 94,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 96,
    ownerOrg: "Apex Extrusions Pvt Ltd",
    ownerGstin: "24AAACA1234B1Z5",
    locationState: "Gujarat",
    locationCity: "Sanand Industrial Area, Ahmedabad",
    spcbJurisdiction: "Gujarat Pollution Control Board (GPCB)",
    hsnCode: "76020010",
    eprCategory: "Non-Ferrous Industrial Stream",
    hazardousFlag: false,
    createdAt: "2026-08-14T09:30:00.000Z",
    verifiedAt: "2026-08-14T11:15:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0x8f3a9e112d4b9671fcae0419280efc9392aa034f195821cde9943261a7eb4431",
    recordHash: "sha256-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    imageUrl: "https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Solar panel mounting rails and framing",
      "Automotive lightweight engine castings",
      "New architectural window and door frames",
    ],
    processingNeeded: ["Magnetic iron separation", "Bale compression", "Furnace melting"],
    visualEvidence: [
      "Clean silver aluminium profiles with pure metal grain",
      "No heavy paint coatings or chemical sealants detected",
      "Zero steel or iron screws attached",
    ],
    carbonImpact: {
      co2eAvoidedKg: 151700, // 8.2 t CO2e avoided per MT of recycled Al
      landfillDivertedMT: 18.5,
      methodologyNote: "Recycling aluminium saves 95% of the electricity needed to mine raw bauxite rock from the ground.",
      emissionFactorUsed: 8.2,
    },
    valuation: {
      basePricePerMT: 198000,
      gradePremium: 12000,
      demandFactor: 5000,
      logisticsFreightCost: 10000,
      estimatedTotalInr: 3792500, // ₹37.92 Lakhs
      currency: "INR",
      disclaimer: "Market price based on Ahmedabad metals exchange and purity grade.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "third_party_verified",
    notes: "Lab spectrometer test confirms 98.4% pure aluminium.",
  },
  {
    id: "CUS-PET-AA-MH",
    title: "Washed Clear Plastic Bottle Flakes (rPET)",
    materialType: "Polyethylene Terephthalate (rPET)",
    category: "plastic",
    grade: "Wash Class AA (Clean & Dry)",
    quantityMT: 24.0,
    reusabilityScore: 91,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 93,
    ownerOrg: "EcoCircle PolyRecycle Ltd",
    ownerGstin: "27AABCE9876C1Z2",
    locationState: "Maharashtra",
    locationCity: "Chakan Industrial Zone, Pune",
    spcbJurisdiction: "Maharashtra Pollution Control Board (MPCB)",
    hsnCode: "39076100",
    eprCategory: "Category 1 Rigid Plastic Packaging",
    hazardousFlag: false,
    createdAt: "2026-08-15T08:00:00.000Z",
    verifiedAt: "2026-08-15T10:45:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0x33b87ad92f025178651cfa861994eec1287413697960bbca61543781290fae49",
    recordHash: "sha256-4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "New recycled water and beverage bottles",
      "Soft polyester yarn for sports shirts & jackets",
      "Transparent packaging trays and boxes",
    ],
    processingNeeded: ["Optical sorting", "Melting and extruding into pellets"],
    visualEvidence: [
      "Even flake size (8-12mm) with high transparency",
      "Zero yellowing or burnt plastic spots",
      "Thoroughly washed with clean hot water",
    ],
    carbonImpact: {
      co2eAvoidedKg: 40800, // 1.7 t CO2e avoided per MT of recycled PET
      landfillDivertedMT: 24.0,
      methodologyNote: "Avoids drilling crude oil to make brand new virgin plastic pellets.",
      emissionFactorUsed: 1.7,
    },
    valuation: {
      basePricePerMT: 82000,
      gradePremium: 4000,
      demandFactor: 2000,
      logisticsFreightCost: 4000,
      estimatedTotalInr: 2016000, // ₹20.16 Lakhs
      currency: "INR",
      disclaimer: "Market price based on Pune industrial plastic recycling rates.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "lab_verified",
    notes: "Batch certified clean with CPCB EPR green recycling credits.",
  },
  {
    id: "CUS-CU-BARLEY-TN",
    title: "Bright Copper Electric Cable Scrap (99.9% Pure)",
    materialType: "Copper Scrap",
    category: "non_ferrous",
    grade: "Barley Bright Clean Wire",
    quantityMT: 12.0,
    reusabilityScore: 98,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 98,
    ownerOrg: "Southern Power Cables Ltd",
    ownerGstin: "33AABCS1234F1Z0",
    locationState: "Tamil Nadu",
    locationCity: "Hosur Industrial Complex",
    spcbJurisdiction: "Tamil Nadu Pollution Control Board (TNPCB)",
    hsnCode: "74040012",
    eprCategory: "High-Value Non-Ferrous Stream",
    hazardousFlag: false,
    createdAt: "2026-08-15T14:20:00.000Z",
    verifiedAt: "2026-08-15T16:00:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0x44c9281729384759102938475619283746591029384756102938475610293847",
    recordHash: "sha256-556677889900aabbccddeeff0011223344556677889900aabbccddeeff001122",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Electric vehicle motor copper windings",
      "High-voltage transformer power coils",
      "Home electrical switchboards & wiring",
    ],
    processingNeeded: ["Direct furnace melting into high-purity copper billets"],
    visualEvidence: [
      "Bright shiny copper strands with zero insulation rubber",
      "No solder, tinning, or brass contaminants",
      "Oxidation-free bright salmon color",
    ],
    carbonImpact: {
      co2eAvoidedKg: 54000, // 4.5 t CO2e avoided per MT of recycled copper
      landfillDivertedMT: 12.0,
      methodologyNote: "Saves 85% of energy compared to mining copper ore deep underground.",
      emissionFactorUsed: 4.5,
    },
    valuation: {
      basePricePerMT: 730000,
      gradePremium: 15000,
      demandFactor: 5000,
      logisticsFreightCost: 10000,
      estimatedTotalInr: 8880000, // ₹88.80 Lakhs
      currency: "INR",
      disclaimer: "Market price based on MCX Copper spot rates.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "third_party_verified",
    notes: "Top-tier electric grade scrap with 99.9% electrical conductivity.",
  },
  {
    id: "CUS-HMS-ISRI-OD",
    title: "Heavy Melting Steel Scrap (Beams, Pipes & Rods)",
    materialType: "Ferrous Steel Scrap",
    category: "ferrous",
    grade: "Heavy Structural Steel (>6mm)",
    quantityMT: 65.0,
    reusabilityScore: 88,
    contaminationRisk: "low",
    condition: "good",
    confidenceScore: 92,
    ownerOrg: "Kalinga Heavy Engineering Corp",
    ownerGstin: "21AABCK4433D1Z9",
    locationState: "Odisha",
    locationCity: "Kalinganagar Steel Complex, Jajpur",
    spcbJurisdiction: "Odisha State Pollution Control Board (OSPCB)",
    hsnCode: "72044900",
    eprCategory: "Ferrous Secondary Resource",
    hazardousFlag: false,
    createdAt: "2026-08-16T11:00:00.000Z",
    verifiedAt: "2026-08-16T13:20:00.000Z",
    verificationStatus: "demo_ledger",
    recordHash: "sha256-ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Electric Arc Furnace TMT steel bars for house construction",
      "Steel alloy casting for machinery parts",
      "Railway track anchors and fittings",
    ],
    processingNeeded: ["Torch cutting to furnace charging size (<1.5m)"],
    visualEvidence: [
      "Heavy structural steel cuts >8mm thickness",
      "Zero galvanized zinc or chrome plating",
      "Dry surface with minimal surface rust",
    ],
    carbonImpact: {
      co2eAvoidedKg: 97500, // 1.5 t CO2e avoided per MT of steel scrap
      landfillDivertedMT: 65.0,
      methodologyNote: "Recycling steel in electric furnaces cuts 70% of greenhouse gases compared to coal blast furnaces.",
      emissionFactorUsed: 1.5,
    },
    valuation: {
      basePricePerMT: 38500,
      gradePremium: 1500,
      demandFactor: 1000,
      logisticsFreightCost: 1500,
      estimatedTotalInr: 2567500, // ₹25.67 Lakhs
      currency: "INR",
      disclaimer: "Market price based on Rourkela and Mandi steel scrap benchmarks.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "user_provided",
  },
  {
    id: "CUS-FA-3812-CG",
    title: "Fine Power Plant Fly Ash Powder (Class F)",
    materialType: "Dry Chimney Fly Ash",
    category: "fly_ash",
    grade: "IS 3812 Class F (Fine Pozzolan)",
    quantityMT: 120.0,
    reusabilityScore: 95,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 97,
    ownerOrg: "Korba Super Thermal Power Station",
    ownerGstin: "22AAACN5566E1Z1",
    locationState: "Chhattisgarh",
    locationCity: "Korba Industrial Area",
    spcbJurisdiction: "Chhattisgarh Environment Conservation Board (CECB)",
    hsnCode: "26211000",
    eprCategory: "Thermal Power Byproduct Stream",
    hazardousFlag: false,
    createdAt: "2026-08-16T14:45:00.000Z",
    verifiedAt: "2026-08-16T16:00:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0xaa1456bf102874139824debb0194837591238471928374659281098234857123",
    recordHash: "sha256-783261765c9284192bce81938502394819284759128374619283475918237461",
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Green Portland Pozzolana Cement (PPC) manufacturing",
      "Lightweight fly ash bricks & mortar for houses",
      "National highway road embankment base",
    ],
    processingNeeded: ["Pneumatic loading into closed dry bulker tankers"],
    visualEvidence: [
      "Super-fine light grey spherical mineral dust",
      "Completely dry and free flowing",
      "Uniform grain size with zero lumps",
    ],
    carbonImpact: {
      co2eAvoidedKg: 96000, // 0.8 t CO2e avoided per MT
      landfillDivertedMT: 120.0,
      methodologyNote: "Directly replaces high-carbon cement clinker made in coal-fired limestone kilns.",
      emissionFactorUsed: 0.8,
    },
    valuation: {
      basePricePerMT: 900,
      gradePremium: 100,
      demandFactor: 50,
      logisticsFreightCost: 200,
      estimatedTotalInr: 114000, // ₹1.14 Lakhs
      currency: "INR",
      disclaimer: "Government MoEFCC eco-friendly guideline rates.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "lab_verified",
  },
  {
    id: "CUS-CDA-383-DL",
    title: "Crushed Concrete Stone Gravel (10-20mm)",
    materialType: "Recycled Stone Aggregate",
    category: "construction_demolition",
    grade: "IS 383 Clean Recycled Coarse Gravel",
    quantityMT: 90.0,
    reusabilityScore: 86,
    contaminationRisk: "low",
    condition: "good",
    confidenceScore: 89,
    ownerOrg: "GreenBuild Circular Infra Ltd",
    ownerGstin: "09AAACG7788F1Z8",
    locationState: "Delhi NCR",
    locationCity: "Noida Sector 68 Processing Plant",
    spcbJurisdiction: "Uttar Pradesh Pollution Control Board (UPPCB)",
    hsnCode: "68109990",
    eprCategory: "Construction Waste Recycling Stream",
    hazardousFlag: false,
    createdAt: "2026-08-17T07:15:00.000Z",
    verifiedAt: "2026-08-17T09:00:00.000Z",
    verificationStatus: "demo_ledger",
    recordHash: "sha256-112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00",
    imageUrl: "https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Footpath interlocking paver blocks & kerbstones",
      "Strong gravel base for highway roads",
      "Non-structural foundation concrete",
    ],
    processingNeeded: ["Screen sorting and water washing to remove fine dust"],
    visualEvidence: [
      "Crushed angular gravel with clean stone edges",
      "Wood, plastic, and dirt removed by magnetic and water separators",
      "Consistent 10mm to 20mm particle sizes",
    ],
    carbonImpact: {
      co2eAvoidedKg: 22500, // 0.25 t CO2e avoided per MT
      landfillDivertedMT: 90.0,
      methodologyNote: "Saves natural granite rocks from being blasted with explosives in mountain quarries.",
      emissionFactorUsed: 0.25,
    },
    valuation: {
      basePricePerMT: 600,
      gradePremium: 50,
      demandFactor: 30,
      logisticsFreightCost: 100,
      estimatedTotalInr: 55800, // ₹55,800
      currency: "INR",
      disclaimer: "Procurement rates benchmarked to Delhi-NCR green construction projects.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "user_provided",
  },
  {
    id: "CUS-GBFS-12089-KA",
    title: "Blast Furnace Slag Sand (GBFS Water-Quenched)",
    materialType: "Slag Mineral Sand",
    category: "slag",
    grade: "IS 12089 Vitrified Slag Sand",
    quantityMT: 140.0,
    reusabilityScore: 93,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 95,
    ownerOrg: "Toranagallu EcoSteel Materials LLP",
    ownerGstin: "29AABCT1122G1Z3",
    locationState: "Karnataka",
    locationCity: "Toranagallu, Ballari",
    spcbJurisdiction: "Karnataka State Pollution Control Board (KSPCB)",
    hsnCode: "26190010",
    eprCategory: "Industrial Mineral Byproduct",
    hazardousFlag: false,
    createdAt: "2026-08-17T12:30:00.000Z",
    verifiedAt: "2026-08-17T15:00:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0x55c9183471029837461928374619283475918237461928374619283475918237",
    recordHash: "sha256-a9b8c7d6e5f41234567890abcdef1234567890abcdef1234567890abcdef1234",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "Ultra-durable marine concrete for sea bridges, ports, and dams",
      "Eco-friendly Portland Slag Cement",
      "Sustainable manufactured sand (M-Sand) replacement",
    ],
    processingNeeded: ["Drying and roller mill fine grinding"],
    visualEvidence: [
      "Clean granulated glassy sand texture from water cooling",
      "Zero iron lumps or heavy dirt",
      "High chemical reactivity for cement bonding",
    ],
    carbonImpact: {
      co2eAvoidedKg: 105000, // 0.75 t CO2e avoided per MT
      landfillDivertedMT: 140.0,
      methodologyNote: "Replaces traditional limestone cement, preventing 105 tons of kiln smoke.",
      emissionFactorUsed: 0.75,
    },
    valuation: {
      basePricePerMT: 1800,
      gradePremium: 100,
      demandFactor: 50,
      logisticsFreightCost: 200,
      estimatedTotalInr: 259000, // ₹2.59 Lakhs
      currency: "INR",
      disclaimer: "Market price aligned with South India green cement grinding plants.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "lab_verified",
  },
  {
    id: "CUS-OCC-11-HR",
    title: "Compressed Brown Cardboard Bales (Clean Kraft)",
    materialType: "Recycled Cardboard Packaging",
    category: "wood",
    grade: "Grade OCC-11 Clean Bales",
    quantityMT: 35.0,
    reusabilityScore: 92,
    contaminationRisk: "low",
    condition: "excellent",
    confidenceScore: 94,
    ownerOrg: "Haryana Circular Paper Mills Ltd",
    ownerGstin: "06AAACH4321E1Z7",
    locationState: "Haryana",
    locationCity: "Manesar, Gurugram",
    spcbJurisdiction: "Haryana State Pollution Control Board (HSPCB)",
    hsnCode: "47071000",
    eprCategory: "Paper Packaging Recycling Stream",
    hazardousFlag: false,
    createdAt: "2026-08-17T16:00:00.000Z",
    verifiedAt: "2026-08-17T17:30:00.000Z",
    verificationStatus: "demo_ledger_anchored",
    ledgerTxHash: "0x77b8192837465918273645192837465918273645192837465918273645192837",
    recordHash: "sha256-3344556677889900aabbccddeeff0011223344556677889900aabbccddeeff00",
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    suggestedApplications: [
      "New brown corrugated shipping boxes for e-commerce parcels",
      "Sturdy egg cartons and fruit packaging trays",
      "Eco-friendly brown kraft shopping bags",
    ],
    processingNeeded: ["Water hydropulping, fiber washing, and sheet pressing"],
    visualEvidence: [
      "Tight square bundles of unprinted brown kraft cardboard",
      "Zero wet moisture, plastic tape, or wax coatings",
      "Long strong paper fibers ideal for recycling",
    ],
    carbonImpact: {
      co2eAvoidedKg: 38500, // 1.1 t CO2e avoided per MT
      landfillDivertedMT: 35.0,
      methodologyNote: "Saves over 340 mature forest trees from being cut down for virgin wood pulp.",
      emissionFactorUsed: 1.1,
    },
    valuation: {
      basePricePerMT: 14000,
      gradePremium: 800,
      demandFactor: 200,
      logisticsFreightCost: 500,
      estimatedTotalInr: 507500, // ₹5.07 Lakhs
      currency: "INR",
      disclaimer: "Market price based on Delhi-NCR paper recycling mill gate rates.",
    },
    lifecycleStage: "recovery",
    evidenceStatus: "third_party_verified",
    notes: "Verified clean kraft cardboard bales from logistics warehouse offcuts.",
  },
];

export const INITIAL_MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: "LIST-AL-6063-01",
    passportId: "CUS-AL-6063-GJ",
    title: "Clean Aluminium Window & Profile Scrap (Grade 6063)",
    materialType: "Aluminium Scrap",
    category: "non_ferrous",
    grade: "Grade 6063 T6 (Clean)",
    quantityMT: 18.5,
    minimumOrderMT: 5.0,
    pricePerMT: 205000,
    totalValueInr: 3792500,
    sellerOrg: "Apex Extrusions Pvt Ltd",
    sellerGstin: "24AAACA1234B1Z5",
    sellerRating: 4.9,
    city: "Sanand (Ahmedabad)",
    state: "Gujarat",
    spcbJurisdiction: "GPCB (Gujarat)",
    hsnCode: "76020010",
    eprEligible: true,
    eprCategory: "Non-Ferrous Industrial Stream",
    imageUrl: "https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 94,
    co2eAvoidedKg: 151700,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-15",
    status: "active",
  },
  {
    id: "LIST-PET-AA-02",
    passportId: "CUS-PET-AA-MH",
    title: "Washed Clear Plastic Bottle Flakes (Food-Grade Clean)",
    materialType: "rPET Flakes",
    category: "plastic",
    grade: "Wash Class AA (Clean & Dry)",
    quantityMT: 24.0,
    minimumOrderMT: 5.0,
    pricePerMT: 84000,
    totalValueInr: 2016000,
    sellerOrg: "EcoCircle PolyRecycle Ltd",
    sellerGstin: "27AABCE9876C1Z2",
    sellerRating: 4.8,
    city: "Pune (Chakan)",
    state: "Maharashtra",
    spcbJurisdiction: "MPCB (Maharashtra)",
    hsnCode: "39076100",
    eprEligible: true,
    eprCategory: "Category 1 Rigid Plastic Packaging",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 91,
    co2eAvoidedKg: 40800,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-16",
    status: "active",
  },
  {
    id: "LIST-CU-BARLEY-03",
    passportId: "CUS-CU-BARLEY-TN",
    title: "Bright Copper Electric Cable Scrap (99.9% Pure)",
    materialType: "Copper Wire Scrap",
    category: "non_ferrous",
    grade: "Barley Bright Wire",
    quantityMT: 12.0,
    minimumOrderMT: 2.0,
    pricePerMT: 740000,
    totalValueInr: 8880000,
    sellerOrg: "Southern Power Cables Ltd",
    sellerGstin: "33AABCS1234F1Z0",
    sellerRating: 5.0,
    city: "Hosur",
    state: "Tamil Nadu",
    spcbJurisdiction: "TNPCB (Tamil Nadu)",
    hsnCode: "74040012",
    eprEligible: true,
    eprCategory: "High-Value Non-Ferrous Stream",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 98,
    co2eAvoidedKg: 54000,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-16",
    status: "active",
  },
  {
    id: "LIST-HMS-8020-04",
    passportId: "CUS-HMS-ISRI-OD",
    title: "Heavy Melting Steel Scrap (Beams, Pipes & Rods)",
    materialType: "Steel Scrap",
    category: "ferrous",
    grade: "Heavy Structural Steel (>6mm)",
    quantityMT: 65.0,
    minimumOrderMT: 20.0,
    pricePerMT: 39500,
    totalValueInr: 2567500,
    sellerOrg: "Kalinga Heavy Engineering Corp",
    sellerGstin: "21AABCK4433D1Z9",
    sellerRating: 4.7,
    city: "Jajpur (Kalinganagar)",
    state: "Odisha",
    spcbJurisdiction: "OSPCB (Odisha)",
    hsnCode: "72044900",
    eprEligible: false,
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 88,
    co2eAvoidedKg: 97500,
    verificationStatus: "demo_ledger",
    listedDate: "2026-08-16",
    status: "active",
  },
  {
    id: "LIST-FA-3812-05",
    passportId: "CUS-FA-3812-CG",
    title: "Fine Power Plant Fly Ash Powder (IS 3812 Class F)",
    materialType: "Fly Ash Powder",
    category: "fly_ash",
    grade: "IS 3812 Class F Pozzolan",
    quantityMT: 120.0,
    minimumOrderMT: 30.0,
    pricePerMT: 950,
    totalValueInr: 114000,
    sellerOrg: "Korba Super Thermal Power Station",
    sellerGstin: "22AAACN5566E1Z1",
    sellerRating: 5.0,
    city: "Korba",
    state: "Chhattisgarh",
    spcbJurisdiction: "CECB (Chhattisgarh)",
    hsnCode: "26211000",
    eprEligible: true,
    eprCategory: "Thermal Power Eco-Byproduct",
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 95,
    co2eAvoidedKg: 96000,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-17",
    status: "active",
  },
  {
    id: "LIST-CDA-383-06",
    passportId: "CUS-CDA-383-DL",
    title: "Crushed Concrete Stone Gravel (10-20mm Clean)",
    materialType: "Recycled Gravel",
    category: "construction_demolition",
    grade: "IS 383 Recycled Coarse Gravel",
    quantityMT: 90.0,
    minimumOrderMT: 20.0,
    pricePerMT: 620,
    totalValueInr: 55800,
    sellerOrg: "GreenBuild Circular Infra Ltd",
    sellerGstin: "09AAACG7788F1Z8",
    sellerRating: 4.6,
    city: "Noida / Greater Noida",
    state: "Delhi NCR",
    spcbJurisdiction: "UPPCB (Uttar Pradesh)",
    hsnCode: "68109990",
    eprEligible: true,
    eprCategory: "Construction Recycling Stream",
    imageUrl: "https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 86,
    co2eAvoidedKg: 22500,
    verificationStatus: "demo_ledger",
    listedDate: "2026-08-17",
    status: "active",
  },
  {
    id: "LIST-GBFS-12089-07",
    passportId: "CUS-GBFS-12089-KA",
    title: "Blast Furnace Slag Sand (GBFS Vitreous)",
    materialType: "GBFS Mineral Sand",
    category: "slag",
    grade: "IS 12089 Slag Sand",
    quantityMT: 140.0,
    minimumOrderMT: 40.0,
    pricePerMT: 1850,
    totalValueInr: 259000,
    sellerOrg: "Toranagallu EcoSteel Materials LLP",
    sellerGstin: "29AABCT1122G1Z3",
    sellerRating: 4.9,
    city: "Ballari",
    state: "Karnataka",
    spcbJurisdiction: "KSPCB (Karnataka)",
    hsnCode: "26190010",
    eprEligible: true,
    eprCategory: "Industrial Mineral Byproduct",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 93,
    co2eAvoidedKg: 105000,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-17",
    status: "active",
  },
  {
    id: "LIST-OCC-11-08",
    passportId: "CUS-OCC-11-HR",
    title: "Compressed Brown Cardboard Bales (Clean Kraft)",
    materialType: "Recycled Cardboard",
    category: "wood",
    grade: "Grade OCC-11 Clean Bales",
    quantityMT: 35.0,
    minimumOrderMT: 10.0,
    pricePerMT: 14500,
    totalValueInr: 507500,
    sellerOrg: "Haryana Circular Paper Mills Ltd",
    sellerGstin: "06AAACH4321E1Z7",
    sellerRating: 4.8,
    city: "Manesar (Gurugram)",
    state: "Haryana",
    spcbJurisdiction: "HSPCB (Haryana)",
    hsnCode: "47071000",
    eprEligible: true,
    eprCategory: "Paper & Packaging Stream",
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
    reusabilityScore: 92,
    co2eAvoidedKg: 38500,
    verificationStatus: "demo_ledger_anchored",
    listedDate: "2026-08-17",
    status: "active",
  },
];

export const INITIAL_MATCH_RECOMMENDATIONS: MatchRecommendation[] = [
  {
    id: "MATCH-AL-01",
    listingId: "LIST-AL-6063-01",
    buyerOrg: "Gujarat Solar Frame Extrusions Ltd",
    buyerType: "Solar Panel & Bicycle Frame Factory",
    buyerCity: "Changodar (Ahmedabad)",
    buyerState: "Gujarat",
    spcbJurisdiction: "GPCB (Gujarat)",
    distanceKm: 28,
    matchScore: 96,
    estimatedFreightInr: 18000,
    whyMatch: {
      materialFit: "This factory specializes in melting Grade 6063 aluminium to make solar panel mounts.",
      quantityFit: "Their furnace needs 15-20 tons per batch. Your 18.5 tons is a perfect match!",
      gradeCompatibility: "98.4% purity matches their strict factory requirements with zero extra cleaning needed.",
      logisticsSummary: "Very close! Just 28 km away on the Sanand-Changodar expressway (1-hour truck ride).",
      carbonSavingsPotential: "151 tons of smoke saved (like taking 33 cars off the road for a full year!).",
      regulatoryAlignment: "Both buyer and seller have active Gujarat Pollution Board green permits.",
    },
    recommendedApplication: "Melting into new solar panel mounting rails and clean bicycle parts.",
    status: "suggested",
  },
  {
    id: "MATCH-PET-02",
    listingId: "LIST-PET-AA-02",
    buyerOrg: "Pune EcoSpinning & Textiles Ltd",
    buyerType: "Recycled Polyester Fabric & Yarn Mill",
    buyerCity: "Baramati",
    buyerState: "Maharashtra",
    spcbJurisdiction: "MPCB (Maharashtra)",
    distanceKm: 95,
    matchScore: 94,
    estimatedFreightInr: 28000,
    whyMatch: {
      materialFit: "They turn clear plastic bottle flakes into soft polyester threads for sports t-shirts.",
      quantityFit: "Your 24-ton batch supplies their yarn spinning line for a full week of production.",
      gradeCompatibility: "Food-grade wash means no glue or dirt, protecting their fine spinning nozzles.",
      logisticsSummary: "95 km direct highway route from Chakan to Baramati.",
      carbonSavingsPotential: "40.8 tons of smoke prevented by replacing virgin petroleum plastic.",
      regulatoryAlignment: "Certified under Maharashtra Plastic Waste Rules with EPR credits.",
    },
    recommendedApplication: "Spinning into soft eco-friendly polyester cloth and sport shirts.",
    status: "suggested",
  },
  {
    id: "MATCH-CU-03",
    listingId: "LIST-CU-BARLEY-03",
    buyerOrg: "Tamil Nadu EV Motor Technologies Ltd",
    buyerType: "Electric Vehicle Motor Manufacturer",
    buyerCity: "Hosur Industrial Zone",
    buyerState: "Tamil Nadu",
    spcbJurisdiction: "TNPCB (Tamil Nadu)",
    distanceKm: 14,
    matchScore: 98,
    estimatedFreightInr: 8000,
    whyMatch: {
      materialFit: "They urgently need pure 99.9% copper wire scrap for electric scooter motor coils.",
      quantityFit: "Your 12-ton lot supplies 8,000 electric vehicle motor windings.",
      gradeCompatibility: "Bright clean wire with zero rubber insulation allows instant melting.",
      logisticsSummary: "Super local! Only 14 km away within Hosur industrial cluster.",
      carbonSavingsPotential: "54 tons of smoke saved compared to digging copper mines.",
      regulatoryAlignment: "Fully certified with green non-ferrous EPR portal tokens.",
    },
    recommendedApplication: "Directly casting into pure copper electric vehicle motor windings.",
    status: "suggested",
  },
  {
    id: "MATCH-FA-04",
    listingId: "LIST-FA-3812-05",
    buyerOrg: "Nuvoco Green Cement Grinding Works",
    buyerType: "Eco-Friendly Cement Manufacturing Plant",
    buyerCity: "Bilaspur",
    buyerState: "Chhattisgarh",
    spcbJurisdiction: "CECB (Chhattisgarh)",
    distanceKm: 85,
    matchScore: 97,
    estimatedFreightInr: 32000,
    whyMatch: {
      materialFit: "They mix power plant fly ash into cement powder to make it stronger and more waterproof.",
      quantityFit: "Their silos accept 100-150 tons daily in closed bulker trucks.",
      gradeCompatibility: "Class F fine powder is lab-tested and perfectly dry.",
      logisticsSummary: "Direct 85 km transit via Korba-Bilaspur industrial highway.",
      carbonSavingsPotential: "96 tons of CO₂ kiln smoke prevented from entering the atmosphere.",
      regulatoryAlignment: "Complies with Central Government 100% Fly Ash Utilization rules.",
    },
    recommendedApplication: "Blending into high-strength Portland Pozzolana Green Cement.",
    status: "suggested",
  },
];

export const INITIAL_OWNERSHIP_EVENTS: OwnershipEvent[] = [
  {
    id: "EVT-1001",
    passportId: "CUS-AL-6063-GJ",
    eventType: "CREATED",
    timestamp: "2026-08-14T09:30:00.000Z",
    actor: "Apex Extrusions Pvt Ltd",
    actorRole: "supplier",
    location: "Sanand, Gujarat",
    notes: "18.5 Tons of clean aluminium window offcuts weighed and photographed at factory gate.",
    txHash: "0x8f3a9e112d4b9671fcae0419280efc9392aa034f195821cde9943261a7eb4431",
    recordHash: "sha256-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    blockNumber: 104830,
    evidenceType: "user_provided",
  },
  {
    id: "EVT-1002",
    passportId: "CUS-AL-6063-GJ",
    eventType: "CLASSIFIED",
    timestamp: "2026-08-14T10:15:00.000Z",
    actor: "CirculAI Vision Engine",
    actorRole: "auditor",
    location: "Cloud Node Mumbai",
    notes: "AI camera analyzed photo: 94/100 cleanliness score, 98.4% pure alloy, low contamination risk.",
    txHash: "0x99a12b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f8",
    recordHash: "sha256-889900aabbccddeeff0011223344556677889900aabbccddeeff0011223344",
    blockNumber: 104831,
    evidenceType: "ai_estimated",
  },
  {
    id: "EVT-1003",
    passportId: "CUS-AL-6063-GJ",
    eventType: "PASSPORT_ISSUED",
    timestamp: "2026-08-14T11:15:00.000Z",
    actor: "GPCB Compliance Audit Division",
    actorRole: "auditor",
    location: "Gandhinagar, Gujarat",
    notes: "Digital ID Card issued with printable QR code tag for truck logistics and pollution board verification.",
    txHash: "0x11223344556677889900aabbccddeeff0011223344556677889900aabbccddeeff",
    recordHash: "sha256-11223344556677889900aabbccddeeff0011223344556677889900aabbccddee",
    blockNumber: 104832,
    evidenceType: "third_party_verified",
  },
  {
    id: "EVT-1004",
    passportId: "CUS-AL-6063-GJ",
    eventType: "LISTED",
    timestamp: "2026-08-15T08:00:00.000Z",
    actor: "Apex Extrusions Pvt Ltd",
    actorRole: "supplier",
    location: "Sanand, Gujarat",
    notes: "Listed on open green marketplace at ₹2,05,000 per ton (Total batch value: ₹37.92 Lakhs).",
    txHash: "0x33445566778899001122aabbccddeeff0011223344556677889900aabbccddeeff",
    recordHash: "sha256-33445566778899001122aabbccddeeff0011223344556677889900aabbccddee",
    blockNumber: 104833,
    evidenceType: "user_provided",
  },
  {
    id: "EVT-1005",
    passportId: "CUS-AL-6063-GJ",
    eventType: "MATCH_OFFER_TRANSMITTED",
    timestamp: "2026-08-15T11:45:00.000Z",
    actor: "Gujarat Solar Frame Extrusions Ltd",
    actorRole: "buyer",
    location: "Changodar, Gujarat",
    notes: "Purchase offer sent for full 18.5 Tons lot to make solar panel mounts.",
    txHash: "0x55667788990011223344aabbccddeeff0011223344556677889900aabbccddeeff",
    recordHash: "sha256-55667788990011223344aabbccddeeff0011223344556677889900aabbccddee",
    blockNumber: 104834,
    evidenceType: "user_provided",
  },
];

export const DEMO_INITIAL_PASSPORTS = INITIAL_MATERIAL_PASSPORTS;
export const DEMO_MARKETPLACE_LISTINGS = INITIAL_MARKETPLACE_LISTINGS;
export const DEMO_MATCH_RECOMMENDATIONS = INITIAL_MATCH_RECOMMENDATIONS;
export const DEMO_OWNERSHIP_EVENTS = INITIAL_OWNERSHIP_EVENTS;
